apiVersion: apps/v1
kind: Deployment
# this is the metadata section
metadata:
  name: webserver
  labels:
    # here we define a key/value pair this has to match the selector below services also reference this label
    app: webserver
# this is the spec section
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webserver
  # the following part is basically a configuration file inside a configuration file ( has its own metadata/spec sections )
  # this is bascially the part of the configuration file that defines the pod 
  template:
    metadata:
      # same functionality as with the label above
      labels:
        app: webserver
    spec:
      containers:
      - name: httpserver
        image: sandeepdocker45/httpserver:v1
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
          limits:
            cpu: 100m
            memory: 25Mi
